[project]
name = "exam5"
version = "0.2.0"
description = "A Django project for managing books and related data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "django-jazzmin>=3.0.1",
    "pillow>=12.0.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.10",
]
