# Generated by Django 6.0 on 2026-02-23 16:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='non-defined-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='non-defined-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(default='non-defined-slug', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 9, 16, 35, 41, 531779), null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RENTED', 'RENTED'), ('ON_TIME', 'ON_TIME'), ('LATE', 'LATE')], max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
