# Generated by Django 6.0 on 2026-02-28 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_author_slug_alter_book_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 14, 10, 17, 45, 205457), null=True),
        ),
    ]
